### ISSUE TITLE
ipc not working on NixOS/Niri Setup

### ISSUE THREAD

**Issue by JasmineLowen** [AvengeMedia/DankMaterialShell#1153]
## Compositor

- [x] niri
- [ ] Hyprland
- [ ] dwl (MangoWC)
- [ ] sway
- [ ] Other (specify)

## Distribution

NixOS (nixos-unstable)

## dms version

dms 1.2-unstable+date=2025-12-24_6303304

## Description

I recently updated and while everything seems to work fine, invoking anything like `dms ipc ...` doesn't work. Just running `dms` gives me

```
 ERROR  go: DankMaterialShell (DMS) is not detected as installed on this system.
  INFO  go: Please install DMS using dankinstall before using this management interface.
```

while running `dms ipc call spotlight toggle` returns

```
No running instances for "/nix/store/i38ljgh10k4n08laf9hc2qq00gnpmwxw-dms-shell-1.2-unstable+date=2025-12-24_6303304/share/quickshell/dms/shell.qml"
 FATAL  go: Error running IPC command: exit status 255
```

I took a look into my processes running and in `btop` I have the following output:

## Expected Behavior

- dms recognizes NixOS and doesn't require dankinstallsince NixOS should handle installation by itself
- the running (wrapped) process is recognized

## Steps to Reproduce

I can provide my locks of all dependencies if wanted, but I'm not sure that would help at the moment and it is more of a general issue with NixOS

## Error Messages/Logs

I'll add logs as soon as I find out how to do that on NixOS. The process is started automatically (suposedly through systemd)

```
Paste error messages or logs here
```

**Comment by Pacman99** [comment]
I noticed this too and I believe its because of the quickshell version that the flake is pinned with.

As a workaround add this to your NixOS or Home-manager config:
```nix
  programs.dankMaterialShell.greeter = {
    quickshell.package = pkgs.quickshell;
  };
```

**Comment by JasmineLowen** [comment]
Unfortunately this didn't really help in my case. Thanks for the tip anyways! ❤️

**Comment by JasmineLowen** [comment]
More info, the systemd logs say the following:

```
● dms.service - DankMaterialShell
     Loaded: loaded (/home/jassylowen/.config/systemd/user/dms.service; enabled; preset: ignored)
     Active: active (running) since Thu 2025-12-25 23:17:40 CET; 12min ago
 Invocation: 3ab14fb9088a4615bb82efaa73b3eaff
   Main PID: 19358 (.dms-wrapped)
      Tasks: 52 (limit: 17730)
     Memory: 169.8M (peak: 183.4M)
        CPU: 16.236s
     CGroup: /user.slice/user-1001.slice/user@1001.service/app.slice/dms.service
             ├─19358 /nix/store/i38ljgh10k4n08laf9hc2qq00gnpmwxw-dms-shell-1.2-unstable+date=2025-12-24_6303304/bin/dms -c /nix/store/i38ljgh10k4n08laf9hc2qq00gnpmwxw-dms-shell-1.2-unstable+date=2025-12-24_6303304/share/quickshell/dms run --session
             └─19365 /nix/store/l8fx3x418vw92sglxmd57hkinyrag81x-quickshell-wrapped-0.2.1/bin/quickshell -p /nix/store/i38ljgh10k4n08laf9hc2qq00gnpmwxw-dms-shell-1.2-unstable+date=2025-12-24_6303304/share/quickshell/dms

Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: CompositorService: Detected Niri with socket: /run/user/1001/niri.wayland-1.2487.sock
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: NiriService: Generated wpblur config at /home/jassylowen/.config/niri/dms/wpblur.kdl
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: Theme: Dynamic colors file loaded successfully
Dec 25 23:17:42 girlpowerhouse dms[19358]:   INFO  go: Done
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: Theme worker: Theme generation completed
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: Theme: Matugen worker completed successfully
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: SessionService: Native inhibitor available: true
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: NiriService: Generated layout config at /home/jassylowen/.config/niri/dms/layout.kdl
Dec 25 23:17:42 girlpowerhouse dms[19365]:   INFO qml: NiriService: Generated alttab config at /home/jassylowen/.config/niri/dms/alttab.kdl
```

**Comment by JasmineLowen** [comment]
> I noticed this too and I believe its because of the quickshell version that the flake is pinned with.
> 
> As a workaround add this to your NixOS or Home-manager config:
> 
>   programs.dankMaterialShell.greeter = {
>     quickshell.package = pkgs.quickshell;
>   };

After all this worked although not the snippet shown here. You really have to set the package in the home manager module not just the nixos greeter module. So both in nixos

```nix
programs.dank-material-shell.greeter.quickshell.package = pkgs.quickshell;
```

and in home manager

```nix
programs.dank-material-shell.quickshell.package = pkgs.quickshell;
```

**Comment by Pacman99** [comment]
Oh right I had changed the greeter package too, but I thought only the home-manager change was actually necessary. It might be good to keep this issue open since its still not working by default.

I would open a PR, but I'm not sure what quickshell features from the pinned commit dms uses. So far everything seems to work fine for me with stable quickshell.

**Comment by purian23** [comment]
Is this still an issue or we're good?

**Comment by JasmineLowen** [comment]
Idk. I just reopened because @Pacman99 said that it would make sense. I didn't notice anything broken while using it over the last few days

**Comment by LuckShiba** [comment]
I can't reproduce this, I use Quickshell from the git build and it works just fine. Maybe this can be a behavior from having more than one Quickshell in your system?

The only similar problems that I can get is when DMS updates and the CLI version doesn't match the running DMS one (which is solved by restarting it), but this doesn't seem to be the case.

**Comment by LuckShiba** [comment]
> Oh right I had changed the greeter package too, but I thought only the home-manager change was actually necessary. It might be good to keep this issue open since its still not working by default.
> 
> I would open a PR, but I'm not sure what quickshell features from the pinned commit dms uses. So far everything seems to work fine for me with stable quickshell.

Idle management, Polkit agent and Keybinds management, quite important features.

**Comment by Pacman99** [comment]
I just updated to the latest commit of dms and removed `quickshell.package = pkgs.quickshell` and I'm still having the ipc issue. I restarted dms and I don't think theres any other quickshell in my system.

I also tried running the ipc command with the exact quickshell command indicated in `systemctl --user status dms`:
```bash
/nix/store/v5q5zg1pkr6g3fkkknqng3f1d413lb4y-quickshell-wrapped-0.2.1/bin/quickshell -p /nix/store/kyp4i5vg2x0cpqrq2ky1jkz13g0jj8gg-dms-shell-1.2-unstable+date=2025-12-28_c281bf3/share/quickshell/dms ipc call spotlight toggle
```

Any chance your nix config is public? I could try to compare to see if theres anything I'm doing different. Mines over at https://gitlab.com/coffeetables/lower and dms config is here https://gitlab.com/coffeetables/lower/-/blob/master/home/desktop/niri/default.nix

**Comment by Joel-Singh** [comment]
dms ipc was also not working for me with the same error message. I had dms installed as the [NixOS module](https://danklinux.com/docs/dankmaterialshell/nixos) but switching to the [Flake/Home Manager Installation](https://danklinux.com/docs/dankmaterialshell/nixos-flake) fixed ipc without needing to do anything irregular like set a different quickshell package.

**Comment by Pacman99** [comment]
> dms ipc was also not working for me with the same error message. I had dms installed as the [NixOS module](https://danklinux.com/docs/dankmaterialshell/nixos) but switching to the [Flake/Home Manager Installation](https://danklinux.com/docs/dankmaterialshell/nixos-flake) fixed ipc without needing to do anything irregular like set a different quickshell package.

Interesting I'm on home-manager already, was there any other change you made while switching to home-manager?

**Comment by LuckShiba** [comment]
@Pacman99, @JasmineLowen, apparently quickshell-git started filtering by the WAYLAND_DISPLAY variable and for some reason, I guess your terminal didn't have this variable and that's why it was failing instead. Can you confirm me if this issue still happens after https://github.com/AvengeMedia/DankMaterialShell/commit/bae32e51ff6d873e51e29fe20fee378714aba150 using the quickshell version from Git?

**Comment by thesleepingsage** [comment]
I opened an issue in the quickshell repo describing the issue [here](https://github.com/quickshell-mirror/quickshell/issues/452).

**Comment by Pacman99** [comment]
That commit did the trick, the issue is fixed for me on latest commit now. `$WAYLAND_DISPLAY` is set in my terminal, but maybe its not set or set with different formatting in the systemd service.

**Comment by abowen** [comment]
> > I noticed this too and I believe its because of the quickshell version that the flake is pinned with.
> > As a workaround add this to your NixOS or Home-manager config:
> > programs.dankMaterialShell.greeter = {
> > quickshell.package = pkgs.quickshell;
> > };
> 
> After all this worked although not the snippet shown here. You really have to set the package in the home manager module not just the nixos greeter module. So both in nixos
> 
> programs.dank-material-shell.greeter.quickshell.package = pkgs.quickshell;
> 
> and in home manager
> 
> programs.dank-material-shell.quickshell.package = pkgs.quickshell;

This workaround worked for me until today when updated my system on unstable

- Flakes
- NixOS
- Home Manager
- DMS & Niri installed via configuration.nix

` ERROR  go: DankMaterialShell (DMS) is not detected as installed on this system.`

Happy to provide any more of my config / error logs. It's a fairly vanilla install

**Comment by cpnfeeny** [comment]
On NixOS with Hyprland, I've been seeing this IPC error for a bit now. The workaround never worked for me, and the problem is both on unstable using configuration.nix or via flake. I'm happy to share any logs or configuration files.

```
❯ dms ipc call audio increment 3
No running instances for "/nix/store/bcylgf855b8vllj4ch6qjcw25z5dyhv4-dms-shell-1.2.2+date=2026-01-14_1b7dcf5/share/quickshell/dms/shell.qml"
 FATAL  go: Error running IPC command: exit status 255
```

```
❯ dms doctor
                                  
██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝ 
██║  ██║██╔══██║██║╚██╗██║██╔═██╗ 
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝

 System Health Check
                    
──────────────────────────────────────
System
    ● Operating System ····· NixOS 26.05 (Yarara)
    ● Architecture ········· amd64
    ● Display Server ······· Wayland

  Versions
    ● DMS CLI ·············· dms 1.2.2+date=2026-01-14_1b7dcf5
    ● Quickshell ··········· quickshell 0.2.1, revision 41828c4180fb921df7992a5405f5ff05d2ac2fff, distributed by: Official-Nix-Flake
    ● DMS Shell ············ 1.2.2+date=2026-01-14_1b7dcf5

  Installation
    ● DMS Configuration ···· Found
    ● shell.qml ············ Present

  Compositor
    ● Hyprland ············· 0.53.1
    ○ Active ··············· Hyprland

  Quickshell Features
    ● Polkit ··············· Available
    ● IdleMonitor ·········· Available
    ● IdleInhibitor ········ Available
    ● ShortcutInhibitor ···· Available

  Optional Features
    ● accountsservice ······ Running
    ● power-profiles-daemon  Running
    ○ I2C/DDC ·············· No monitors detected
    ● Terminal ············· ghostty
    ● matugen ·············· Installed
    ● dgop ················· Installed
    ● cava ················· Installed
    ● khal ················· Installed
    ● Network ·············· NetworkManager (active)
    ○ danksearch ··········· Not installed
    ● loginctl ············· Installed
    ○ fprintd ·············· Not installed

  Config Files
    ● settings.json ········ Present
    ○ clsettings.json ······ Not yet created
    ○ plugin_settings.json · Not yet created
    ● session.json ········· Present
    ● dms-colors.json ······ Present

  Services
    ● dms.service ·········· enabled, active
    ● greetd ··············· enabled

  Environment
    ○ QT_QPA_PLATFORMTHEME · gtk3

  ──────────────────────────────────────
  ✓ All checks passed!
```

**Comment by JasmineLowen** [comment]
@cpnfeeny I think it would be better of you open another issue. This here is related to a very specific setup using NixOS and **_Niri_** which is both specified in the issue title and description. Solutions to one problem don't necessarily translate for other setup.

**Comment by LuckShiba** [comment]
@cpnfeeny have you tried restarting DMS? (`systemctl --user restart dms`) or does this happen all the time?

the IPC don't work if it was updated and the service wasn't restarted

**Comment by cpnfeeny** [comment]
> [@cpnfeeny](https://github.com/cpnfeeny) I think it would be better of you open another issue. This here is related to a very specific setup using NixOS and **_Niri_** which is both specified in the issue title and description. Solutions to one problem don't necessarily translate for other setup.

As suggested, I started [another issue](https://github.com/AvengeMedia/DankMaterialShell/issues/1372).
