### ISSUE TITLE
Brightness buttons do not work

### ISSUE THREAD

**Issue by Tertle950** [AvengeMedia/DankMaterialShell#1218]
### Compositor

- [x] Niri
- [ ] Hyprland
- [ ] MangoWC (dwl)
- [ ] Sway

### Distribution

- [ ] Arch Linux
- [ ] CachyOS
- [ ] Fedora
- [ ] NixOS
- [ ] Debian
- [ ] Ubuntu
- [ ] Gentoo
- [ ] OpenSUSE
- [x] Other (specify below)

### If Other, please specify

EndeavorOS (installed without desktop environment)

### dms version

1.0.3

### Description

Same as issue title.

I suspect it has something to do with the fact that, once I save the Keyboard Shortcut, the action changes to `dms ipc call brightness [decrement/increment] 10`, but running that exact command on my terminal results in this error:
```
Too few arguments provided (2 required but 1 were provided.)
Function definition: function [decrement/increment](step: string, device: string): string
```

(Temporary workaround: manually enter command with device name included, get device name with `dms brightness list`. I only have one display anyway)

### Expected Behavior

Brightness Up and Down buttons increment and decrement the brightness by 10%.

### Steps to Reproduce & Installation Method

1. Change XF86MonBrightnessDown action to DMS' own Brightness Down (10%)
  a. Brightness Down button works, Brightness Up button doesn't
2. Change XF86MonBrightnessUp action to DMS' own Brightness Up (10%)
  a. Brightness Up button works, Brightness Down button doesn't
3. Reboot the computer
  a. Neither button works

**Comment by undett** [comment]
I had the exact same problem. Try to specify a device whose brightness can be adjusted.

<img width="1350" height="1290" alt="Image" src="https://github.com/user-attachments/assets/29b63965-cd90-4a3c-94e9-873602699662" />

**Comment by bbedward** [comment]
fixed in db1de9df386a9d958da1cedc6eb716f71aa2967c

**Comment by venttarc** [comment]
@undett i dont have the option called "keyboard shortcuts" in my dms settings. How do i get that?

**Comment by undett** [comment]
@venttarc If you have an arch-based distro, install the `quickshell-git` package from the AUR, then restart dms.

**Comment by venttarc** [comment]
@undett thanks, and yes i use arch based distro. But i wanted to ask something, is "keyboard shortcut"  not available because it is still not out as release yet? I installed QS from my package repo.

**Comment by undett** [comment]
@venttarc you need exactly the `quickshell-git` from AUR, it's newer version with new features. With regular QS the `keyboard shortcut` will not appear.
