### ISSUE TITLE
Middle section of the topbar seems to be broken

### ISSUE THREAD

**Issue by folke** [AvengeMedia/DankMaterialShell#244]
All the widgets from the middle section of the topbar seem to be aligned at the left of the bar since today.

any ideas? Do let me know if you need any extra info..

<img width="1171" height="163" alt="Image" src="https://github.com/user-attachments/assets/09d3b19b-e9a9-4107-82ec-197b7ed5d7ed" />

## Compositor

- [x] niri
- [ ] Hyprland
- [ ] Other (specify)

## Steps to Reproduce

1.
2.
3.

## Error Messages/Logs

```
Paste error messages or logs here
```

**Comment by bbedward** [comment]
I think it was re-fixed in this one c04177e45d529440dee8ea257f335198fe8425fd

**Comment by folke** [comment]
I'm on the latest commit. Also see startup log:

```
❯ dms run

██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝
██║  ██║██╔══██║██║╚██╗██║██╔═██╗
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
  INFO: Launching config: "/etc/xdg/quickshell/dms/shell.qml"
  INFO: Shell ID: "8d5a47ead22af78707b30ad620bae58f" Path ID "8d5a47ead22af78707b30ad620bae58f"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/0a92a8523t/log.qslog"
 DEBUG qml: IdleService: Initialized with idle monitoring support
  INFO: Configuration Loaded
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined (exception occurred during delayed function evaluation)
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/folke/.local/state/DankMaterialShell/notepad-files/untitled-1758030596498.txt failed: File does not exist.
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/folke/.local/state/DankMaterialShell/notepad-files/untitled-1758030596498.txt failed: File does not exist.
 DEBUG qml: CompositorService: Detected Niri with socket: /run/user/1000/niri.wayland-1.1257.sock
 DEBUG qml: SessionService: Elogind detection exited with code 1
 DEBUG qml: DisplayService: ddcutil not available
 DEBUG qml: Detected distribution: CachyOS
 DEBUG qml: Adding ref for module: cpu count: 1
 DEBUG qml: Found session path: /org/freedesktop/login1/session/_31
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined (exception occurred during delayed function evaluation)
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined (exception occurred during delayed function evaluation)
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: DisplayService: geoclue available: true
 DEBUG qml: Current WiFi signal strength: 74
 DEBUG qml: Current WiFi SSID: 74:FL
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
  WARN scene: @Modules/TopBar/TopBar.qml[631:-1]: TypeError: Cannot read property 'width' of undefined
```

**Comment by Vantesh** [comment]
Same here, only occurs when no media is playing

**Comment by folke** [comment]
Can confirm. Playing any media, fixes the topbar

**Comment by bbedward** [comment]
Fixed in this one 7a7d7d053a999250a669057ffd5dbfa8d0d4bdfa

**Comment by folke** [comment]
The errors seem to be fixed, but the topbar still looks as in my screenshot.
But playing any media, makes it look fine

**Comment by bbedward** [comment]
> The errors seem to be fixed, but the topbar still looks as in my screenshot. But playing any media, makes it look fine

I was easily able to reproduce which is why I was confident it fixed it, now I can't. Does a full shell restart fix it? If not can you share which widgets you use on the top bar.

**Comment by folke** [comment]
A restart doesn't fix it.

<details><summary>settings.json</summary>

```json
{
  "currentThemeName": "blue",
  "customThemeFile": "",
  "topBarTransparency": 0.84,
  "topBarWidgetTransparency": 0.59,
  "popupTransparency": 0.92,
  "dockTransparency": 1,
  "use24HourClock": true,
  "useFahrenheit": false,
  "nightModeEnabled": false,
  "weatherLocation": "40.7128, -74.0060",
  "weatherCoordinates": "40.7128,-74.0060",
  "useAutoLocation": true,
  "weatherEnabled": true,
  "showLauncherButton": true,
  "showWorkspaceSwitcher": true,
  "showFocusedWindow": true,
  "showWeather": true,
  "showMusic": true,
  "showClipboard": true,
  "showCpuUsage": true,
  "showMemUsage": true,
  "showCpuTemp": true,
  "showGpuTemp": true,
  "selectedGpuIndex": 0,
  "enabledGpuPciIds": [],
  "showSystemTray": true,
  "showClock": true,
  "showNotificationButton": true,
  "showBattery": true,
  "showControlCenterButton": true,
  "controlCenterShowNetworkIcon": true,
  "controlCenterShowBluetoothIcon": true,
  "controlCenterShowAudioIcon": true,
  "controlCenterWidgets": [
    {
      "id": "volumeSlider",
      "enabled": true,
      "width": 50
    },
    {
      "id": "brightnessSlider",
      "enabled": true,
      "width": 50
    },
    {
      "id": "wifi",
      "enabled": true,
      "width": 50
    },
    {
      "id": "bluetooth",
      "enabled": true,
      "width": 50
    },
    {
      "id": "audioOutput",
      "enabled": true,
      "width": 50
    },
    {
      "id": "audioInput",
      "enabled": true,
      "width": 50
    },
    {
      "id": "nightMode",
      "enabled": true,
      "width": 50
    },
    {
      "id": "darkMode",
      "enabled": true,
      "width": 50
    }
  ],
  "showWorkspaceIndex": false,
  "showWorkspacePadding": true,
  "showWorkspaceApps": true,
  "maxWorkspaceIcons": 3,
  "workspacesPerMonitor": true,
  "workspaceNameIcons": {},
  "waveProgressEnabled": true,
  "clockCompactMode": false,
  "focusedWindowCompactMode": false,
  "runningAppsCompactMode": true,
  "runningAppsCurrentWorkspace": true,
  "clockDateFormat": "",
  "lockDateFormat": "",
  "mediaSize": 1,
  "topBarLeftWidgets": [
    {
      "id": "launcherButton",
      "enabled": true
    },
    {
      "id": "workspaceSwitcher",
      "enabled": true
    },
    {
      "id": "focusedWindow",
      "enabled": true
    },
    {
      "id": "runningApps",
      "enabled": false
    }
  ],
  "topBarCenterWidgets": [
    {
      "id": "notificationButton",
      "enabled": true
    },
    {
      "id": "clock",
      "enabled": true
    },
    {
      "id": "weather",
      "enabled": true
    },
    {
      "id": "music",
      "enabled": true
    }
  ],
  "topBarRightWidgets": [
    "systemTray",
    "clipboard",
    "cpuUsage",
    "battery",
    {
      "id": "controlCenterButton",
      "enabled": true,
      "showNetworkIcon": true,
      "showBluetoothIcon": true,
      "showAudioIcon": true
    }
  ],
  "appLauncherViewMode": "list",
  "spotlightModalViewMode": "list",
  "networkPreference": "auto",
  "iconTheme": "System Default",
  "useOSLogo": false,
  "osLogoColorOverride": "#ffffff",
  "osLogoBrightness": 0.5,
  "osLogoContrast": 1,
  "wallpaperDynamicTheming": true,
  "fontFamily": "Inter Variable",
  "monoFontFamily": "Fira Code",
  "fontWeight": 400,
  "fontScale": 1.1,
  "notepadUseMonospace": true,
  "notepadFontFamily": "",
  "notepadFontSize": 14,
  "notepadShowLineNumbers": false,
  "notepadTransparencyOverride": -1,
  "notepadLastCustomTransparency": 0.95,
  "gtkThemingEnabled": false,
  "qtThemingEnabled": false,
  "showDock": false,
  "dockAutoHide": false,
  "cornerRadius": 8,
  "notificationOverlayEnabled": true,
  "topBarAutoHide": false,
  "topBarOpenOnOverview": false,
  "topBarVisible": true,
  "topBarSpacing": 0,
  "topBarBottomGap": 0,
  "topBarInnerPadding": 0,
  "topBarSquareCorners": true,
  "topBarNoBackground": false,
  "topBarGothCornersEnabled": false,
  "lockScreenShowPowerActions": true,
  "hideBrightnessSlider": false,
  "widgetBackgroundColor": "sth",
  "notificationTimeoutLow": 5000,
  "notificationTimeoutNormal": 5000,
  "notificationTimeoutCritical": 0,
  "screenPreferences": {}
}
```

</details>

**Comment by bbedward** [comment]
Ty, give this one a try e9a61a4f810dfbac1daa25ff1c4b5c92c3d92b65

**Comment by folke** [comment]
Fixed, thank you!
