### ISSUE TITLE
`lock before suspend` does not work

### ISSUE THREAD

**Issue by bokicoder** [AvengeMedia/DankMaterialShell#382]
## Compositor

- [x] niri
- [ ] Hyprland
- [ ] Other (specify)

## Description

After suspending the system and waking it up, the screen was not locked, and after that, whether through IPC or the control center, the screen could no longer be locked unless the DMS was restarted.

But if you lock the screen first and then suspend the system, there is no issue.

**Comment by bbedward** [comment]
It requires `gdbus` to be able to access loginctl dbus interfaces, unless you start the shell with `dms run` which provides native dbus connections (for lock before suspend and other things)

For this issue, logs would be helpful. You can grab them by.

```bash
dms kill
mkdir ~/dms_logs
nohup dms run > ~/dms_logs/dms-$(date +%s).txt 2>&1 &
```

Then once you trigger the issue you can share the contents of ~/dms_logs/dms-<ts>.txt

**Comment by bokicoder** [comment]
@bbedward 

[dms-1760193778.txt](https://github.com/user-attachments/files/22864836/dms-1760193778.txt)

**Comment by bbedward** [comment]
Is there a chance its running without access to $XDG_SESSION_ID ? Logs dont say much, I may need to add some more debug output to it

**Comment by bbedward** [comment]
You can also check `loginctl lock-session $XDG_SESSION_ID` see if that works - that would at least show loginctl is connected

**Comment by bokicoder** [comment]
> 你也可以检查 `loginctl lock-session $XDG_SESSION_ID` 看看是否有效 - 那至少能显示 loginctl 是否已连接

It works

**Comment by bokicoder** [comment]
@bbedward I logged and reviewed the dbus messages and found that there are no corresponding dbus calls after waking up from a suspended state, regardless of how the screen is locked

**Comment by bbedward** [comment]
I can't reproduce it, but I think I'm going to do some enhancements to have the go side create a sleep inhibitor to help guarantee we get the prepare for sleep event and have enough time to lock.

We dont really care about any wakeup signals here, just want the loginctl notification that the system is preparing for suspending.

**Comment by bokicoder** [comment]
> We dont really care about any wakeup signals here, just want the loginctl notification that the system is preparing for suspending.

This?
<img width="1201" height="233" alt="Image" src="https://github.com/user-attachments/assets/ac600a28-219b-4929-9526-a42ce04492b0" />

<img width="388" height="953" alt="Image" src="https://github.com/user-attachments/assets/de1a1bc0-a3b0-4ce7-ae52-914925eb6303" />

**Comment by bbedward** [comment]
That is the one that it is listening to right now, I'm re-engineering this to include a sleep inhibitor and change some structure around - I suspect the issue might be that systemd is not giving enough time for the lock screen to show up (due to lack of sleep inhibitor bein created, telling systemd we need some time to prepare)

**Comment by bbedward** [comment]
I did d a suite of breaking API changes 3a7777c6431de17c38cb5a457c972675f32fb491 

It includes this work, as well. Remove prepare for sleep handling from QML entirely, dms dbus connection creates a sleep inhibitor and handles locking, if lock before suspend is enabled.

I would see - if that handles it.

If still no - you can do DMS_VERBOSE_LOGGING=1 dms run... to get more verbose logs to see whats up

**Comment by bokicoder** [comment]
<img width="560" height="286" alt="Image" src="https://github.com/user-attachments/assets/074767cf-96dd-409a-9e3c-a46b2220d322" />

```
                                  
██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝ 
██║  ██║██╔══██║██║╚██╗██║██╔═██╗ 
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
  INFO  go: DMS API Server listening on: /run/user/1000/danklinux-8827.sock
  INFO  go: Protocol: JSON over Unix socket
  INFO  go: Request format: {"id": <any>, "method": "...", "params": {...}}
  INFO  go: Response format: {"id": <any>, "result": {...}} or {"id": <any>, "error": "..."}
  INFO  go: Loginctl manager initialized
  INFO  go: Network manager initialized
  INFO  go: Freedesktop manager initialized
  INFO: Launching config: "/nix/store/kw7m4j0m01fm01js7jc2ncdrkkafpkx6-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/shell.qml"
  INFO: Shell ID: "a86c01df418a6abf0d7c249380a3abc7" Path ID "a86c01df418a6abf0d7c249380a3abc7"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/ht6vrzz3t/log.qslog"
 DEBUG qml: NetworkService: Initializing...
 DEBUG qml: NetworkService: DMS_SOCKET found, waiting for capabilities...
  INFO: Configuration Loaded
  WARN scene: QML FileView at @Common/SettingsData.qml[1503:5]: Read of /home/super6/.config/DankMaterialShell/plugin_settings.json failed: File does not exist.
  WARN scene: QML FileView at @Common/Theme.qml[896:5]: Read of /home/super6/.cache/quickshell/dankshell/dms-colors.json failed: File does not exist.
 DEBUG qml: I18n: Using locale 'zh_CN' from file:///nix/store/kw7m4j0m01fm01js7jc2ncdrkkafpkx6-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/translations/poexports/zh_CN.json
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/super6/.local/state/DankMaterialShell/notepad-files/untitled-1760161840695.txt failed: File does not exist.
 DEBUG qml: I18n: Loaded translations for 'zh_CN' (463 contexts)
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/super6/.local/state/DankMaterialShell/notepad-files/untitled-1760161840695.txt failed: File does not exist.
 DEBUG qml: Detected distribution: NixOS 25.11 (Xantusia)
 DEBUG qml: Adding ref for module: cpu count: 1
 DEBUG qml: Adding ref for module: memory count: 1
 DEBUG qml: Adding ref for module: cpu count: 2
 DEBUG qml: Adding ref for module: memory count: 2
 DEBUG  go: DMS API Request: method=subscribe id=0
 ERROR  go: DMS API Error: id=0 error=unknown method: subscribe
 ERROR qml: DMSService: Server does not support subscribe method
 DEBUG qml: IdleService: Initialized with idle monitoring support
 DEBUG qml: CompositorService: Detected Niri with socket: /run/user/1000/niri.wayland-1.1873.sock
 DEBUG qml: NiriService: Generating binds config...
  WARN qml: NiriService: Failed to write binds config, exit code: 1
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: SessionService: Native inhibitor available: true
 DEBUG qml: NiriService: Generating layout config...
 DEBUG qml: NiriService: Generated layout config at /home/super6/.config/niri/dms/layout.kdl
 DEBUG qml: SessionService: Elogind detection exited with code 1
 DEBUG qml: DankBar: Created native Wayland IdleInhibitor for eDP-1
```

**Comment by bbedward** [comment]
Whole package needs an update, dms CLI + the qml

**Comment by bokicoder** [comment]
I know about this, but I was negligent when handling it. It's my fault.

**Comment by bokicoder** [comment]
Now it's the lock screen that appears first, then the system waits for about 4 seconds before suspending, Is this normal?

**Comment by bbedward** [comment]
it's normal right now (because the lock screen isnt releasing the inhibitor) - which is one remaining enhancement. ONce lock screen is fully displayed & ready - it should release the inhibitor and then it wont delay as long.

**Comment by bokicoder** [comment]
I see. Thank you.

**Comment by bbedward** [comment]
New release, v0.1.2 properly releases the inhibitor when the lock screen is loaded, removing the delay. It also requires another update to dms binary to get to API v2 (but doesnt brick any functionality, besides the delay).

I think we're good on the dms API syncing and qml side now so we can push API updates without breaking changes.

These things are not provided by quickshell, at all, so that's why dms is coming in and providing a native dbus interface to loginctl, accountsservice, networkmanager (its not required still, but its required to extend functionality to support things like this)

**Comment by bokicoder** [comment]
> New release, v0.1.2 properly releases the inhibitor when the lock screen is loaded, removing the delay. It also requires another update to dms binary to get to API v2 (but doesnt brick any functionality, besides the delay).
> 
> I think we're good on the dms API syncing and qml side now so we can push API updates without breaking changes.
> 
> These things are not provided by quickshell, at all, so that's why dms is coming in and providing a native dbus interface to loginctl, accountsservice, networkmanager (its not required still, but its required to extend functionality to support things like this)

No, this has caused the issue to recur.

**Comment by bokicoder** [comment]
```
                                  
██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝ 
██║  ██║██╔══██║██║╚██╗██║██╔═██╗ 
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
  INFO  go: DMS API Server listening on: /run/user/1000/danklinux-3425.sock
  INFO  go: Protocol: JSON over Unix socket
  INFO  go: Request format: {"id": <any>, "method": "...", "params": {...}}
  INFO  go: Response format: {"id": <any>, "result": {...}} or {"id": <any>, "error": "..."}
  INFO  go: Freedesktop manager initialized
  INFO  go: Network manager initialized
  INFO  go: Loginctl manager initialized
  INFO: Launching config: "/nix/store/7cs6hj4hd73j32cjijbdj1ay688pjys7-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/shell.qml"
  INFO: Shell ID: "1395eb9a15573668b3a6c7c3d1918a76" Path ID "1395eb9a15573668b3a6c7c3d1918a76"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/fn2htt04t/log.qslog"
 DEBUG qml: NetworkService: Initializing...
 DEBUG qml: NetworkService: DMS_SOCKET found, waiting for capabilities...
  INFO: Configuration Loaded
  WARN scene: QML FileView at @Common/SettingsData.qml[1503:5]: Read of /home/super6/.config/DankMaterialShell/plugin_settings.json failed: File does not exist.
  WARN scene: QML FileView at @Common/Theme.qml[896:5]: Read of /home/super6/.cache/quickshell/dankshell/dms-colors.json failed: File does not exist.
 DEBUG qml: I18n: Using locale 'zh_CN' from file:///nix/store/7cs6hj4hd73j32cjijbdj1ay688pjys7-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/translations/poexports/zh_CN.json
 DEBUG qml: I18n: Loaded translations for 'zh_CN' (463 contexts)
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/super6/.local/state/DankMaterialShell/notepad-files/untitled-1760250993595.txt failed: File does not exist.
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of /home/super6/.local/state/DankMaterialShell/notepad-files/untitled-1760250993595.txt failed: File does not exist.
 DEBUG qml: Detected distribution: NixOS 25.11 (Xantusia)
 DEBUG qml: Adding ref for module: cpu count: 1
 DEBUG qml: Adding ref for module: memory count: 1
 DEBUG qml: Adding ref for module: cpu count: 2
 DEBUG qml: Adding ref for module: memory count: 2
 DEBUG  go: DMS API Request: method=subscribe id=0
 DEBUG  go: DMS API Request: method=loginctl.getState id=1760276214479
 DEBUG  go: DMS API Request: method=loginctl.setLockBeforeSuspend id=1760276214480
 DEBUG qml: NetworkService: Network capability detected, using NetworkManagerService
 DEBUG qml: NetworkService: Switched to NetworkManagerService, networkAvailable: true
 DEBUG qml: DMSService: Connected (API v2) - ["plugins","network","loginctl","freedesktop"]
 DEBUG  go: DMS API Request: method=network.getState id=1760276214481
 DEBUG qml: SessionService: Synced lock before suspend: true
 DEBUG  go: DMS API Request: method=network.wifi.scan id=1760276214483
 DEBUG  go: DMS API Request: method=network.getState id=1760276214512
 DEBUG qml: IdleService: Initialized with idle monitoring support
 DEBUG qml: CompositorService: Detected Niri with socket: /run/user/1000/niri.wayland-1.1881.sock
 DEBUG qml: NiriService: Generating binds config...
  WARN qml: NiriService: Failed to write binds config, exit code: 1
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: SessionService: Native inhibitor available: true
 DEBUG qml: NiriService: Generating layout config...
 DEBUG qml: NiriService: Generated layout config at /home/super6/.config/niri/dms/layout.kdl
 DEBUG qml: SessionService: Elogind detection exited with code 1
 DEBUG qml: DankBar: Created native Wayland IdleInhibitor for eDP-1
 DEBUG  go: DMS API Request: method=freedesktop.getState id=1760276223917
 DEBUG  go: DMS API Request: method=freedesktop.getState id=1760276223918
 DEBUG  go: DMS API Request: method=loginctl.lockerReady id=1760276223923
 DEBUG qml: LockScreenContent: Locker ready signaled, inhibitor released
 DEBUG  go: DMS API Request: method=freedesktop.settings.getColorScheme id=1760276223925
```

**Comment by bokicoder** [comment]
@bbedward To troubleshoot the issue, I tried using dms locker alongside swayidle. Interestingly, there were no issues at all, which suggests...

**Comment by bokicoder** [comment]
Further troubleshooting:

dms with loginctl lock integration disabled + swayidle using the following configuration = works as expected
```
before-sleep "loginctl lock-session"
lock "dms ipc call lock lock"
```


dms with loginctl lock integration enabled + swayidle using the following configuration = does not work as expected
```
before-sleep "loginctl lock-session"
```

The "lock before suspend" feature in dms was disabled in both of the above scenarios.

**Comment by bokicoder** [comment]
@bbedward I can confirm that the issue lies with dms's loginctl lock integration. When dms's loginctl lock integration is enabled, running the commands `loginctl lock-session && systemctl suspend` in the terminal fails to lock the screen.

**Comment by blurgyy** [comment]
I did a bisect earlier and pinpointed the commit that broke `loginctl lock-session $XDG_SESSION_ID` to be 3a7777c6431de17c38cb5a457c972675f32fb491.

Issue: #393

**Comment by bokicoder** [comment]
> I did a bisect earlier and pinpointed the commit that broke `loginctl lock-session $XDG_SESSION_ID` to be [3a7777c](https://github.com/AvengeMedia/DankMaterialShell/commit/3a7777c6431de17c38cb5a457c972675f32fb491).
> 
> Issue: [#393](https://github.com/AvengeMedia/DankMaterialShell/issues/393)

https://github.com/AvengeMedia/DankMaterialShell/issues/382#issuecomment-3393580013

The issue you're experiencing is quite strange. When I run the `loginctl lock-session` command alone, it works without any problems.

**Comment by blurgyy** [comment]
> The issue you're experiencing is quite strange. When I run the `loginctl lock-session` command alone, it works without any problems.

Thanks for the input. May I ask which commit did you test it on?

**Comment by bokicoder** [comment]
> Thanks for the input. May I ask which commit did you test it on?

It is the latest commit.

**Comment by blurgyy** [comment]
It appears after said commit, I must use `dms run` (which in turn runs quickshell by itself) to be able to lock session with loginctl. Is `dms run` now mandatory to get DankMaterialShell working? I'm fine switching to it but it'd be good to know if the previous plain quickshell setup is still supported or not.

**Comment by bokicoder** [comment]
> It appears after said commit, I must use `dms run` (which in turn runs quickshell by itself) to be able to lock session with loginctl. Is `dms run` now mandatory to get DankMaterialShell working? I'm fine switching to it but it'd be good to know if the previous plain quickshell setup is still supported or not.

For all features to be available, please use `dms run`.

**Comment by bokicoder** [comment]
@blurgyy Since you're here, let me ask: can you reproduce my situation?

**Comment by blurgyy** [comment]
> @blurgyy Since you're here, let me ask: can you reproduce my situation?

Hey @bokicoder, I have personally never used suspend, so I might not be able to provide relevant information here.

**Comment by bbedward** [comment]
it's interesting that - it worked with the sleep inhibitor, but not when toggling the sleep inhibitor off. Can you verify its existence with `systemd-inhibit --list`

<img width="1204" height="186" alt="Image" src="https://github.com/user-attachments/assets/7e6dfe24-2d0a-45f2-ab7b-58db9eb570cd" />

(I'm not able to reproduce the situation), but I'm not sure why `loginctl lock-session` would work, but `loginctl lock-session && systemctl suspend` wouldn't lock? Also it seemed to work with the sleep inhibitor, but not when the lock surface is releasing the sleep inhibitor

**Comment by bokicoder** [comment]
> it's interesting that - it worked with the sleep inhibitor, but not when toggling the sleep inhibitor off. Can you verify its existence with `systemd-inhibit --list`

<img width="1091" height="172" alt="Image" src="https://github.com/user-attachments/assets/d69d3c73-71c5-4ffe-b7df-0f6d1ebd9b18" />

**Comment by bokicoder** [comment]
I also tried running the command `loginctl lock-session && sleep 0.1 && systemctl suspend`. The expected behavior was a 0.1-second delay, but in reality, I experienced a delay of approximately 4 seconds at the lock screen interface. This aligns with the issue described in https://github.com/AvengeMedia/DankMaterialShell/issues/382#issuecomment-3393884798. It's really bizarre yet interesting.

**Comment by bokicoder** [comment]
Or try locking the screen first, then suspending the system through the power menu in the lower-left corner. Guess what? It also takes about 4 seconds.

**Comment by bbedward** [comment]
I'm not really able to reproduce the loginctl issue, though I enhhanced the sleep inhibitor to always be released when the lock screen is up - not just in the PrepareForSleep signal: https://github.com/AvengeMedia/danklinux/commit/4254cf910eb41472cc92cdadb61b8514092a2aad

The way this basically works is - as of above commit, in no particular order
- DMS creates a sleep inhibitor  (the one you see in `systemd-inhibit --list`
- When lock screen itself is drawn - it signals to release the inhibitor - if session is locked, it is released.
- On systemctl PrepareForSleep - dms is signaled and locks (which releases the inhibitor), which tells systemd it doesnt have to wait for us anymore.

You can sort of prove it, on latest commits above, by seeing.

```
# Shows DankMaterialShell sleep inhibitor
systemd-inhibit --list 

# Lock & verify inhibitor is gone
loginctl lock-session $XDG_SESSION_ID && sleep 0.2 && systemd-inhibit --list && loginctl unlock-session $XDG_SESSION_ID

# Should not see the DankMaterialShell inhibitor in that 0.2 seconds
```

So that one, would unblock the 4/5 second delay (unless something else is holding an inhibitor)

I'm going to do a release shortly with these changes

**Comment by bokicoder** [comment]
Yep.

<img width="1122" height="162" alt="Image" src="https://github.com/user-attachments/assets/f8e90214-e415-4c1c-9c6a-a1ab0a677e1f" />


Now only the "lock before suspend does not work" issue remains, but I can work around it by using swayidle. So let's take our time and wait to see if anyone can reproduce my problem.

**Comment by bbedward** [comment]
Check this one 4bc05e70830a66886a254c51d7ecfb3b8af082d0 

Explicitly adds it to the IdleManager, in addition to the standard signal.

**Comment by bokicoder** [comment]
It only successfully locked the screen the first time I attempted to suspend; after that, the issue reappeared.

**Comment by bokicoder** [comment]
> So that one, would unblock the 4/5 second delay (unless something else is holding an inhibitor)

However, when the dms sleep inhibitor is active (loginctl integration enabled), a delay occurs even when I only intend to suspend the system.

**Comment by bbedward** [comment]
I wonder if something on the nix configuration is breaking the dbus connection, or something else is interfering and persisting the session lock state.

In the events it stops working, what does `loginctl show-session $XDG_SESSION_ID` say ?

**Comment by bokicoder** [comment]
> I wonder if something on the nix configuration is breaking the dbus connection, or something else is interfering and persisting the session lock state.

I configured the system to use dbus-broker. Could this be having an impact? Beyond that, I'm not sure what else might be relevant.

> In the events it stops working, what does `loginctl show-session $XDG_SESSION_ID` say ?

I suspended the system and the screen lock failed. After waking, I'm unable to lock the screen. The output is:
```
Id=3
User=1000
Name=super6
Timestamp=Thu 2025-10-16 21:42:19 CST
TimestampMonotonic=21532115
VTNr=1
Seat=seat0
TTY=tty1
Remote=no
Service=greetd
Scope=session-3.scope
Leader=1735
Audit=3
Type=wayland
Class=user
Active=yes
State=active
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
CanIdle=yes
CanLock=yes
LockedHint=no
```

**Comment by bbedward** [comment]
I think I understand what's going on, and hope that this fixes it https://github.com/AvengeMedia/danklinux/commit/08aa6c16ac4f83425e7701086d0987c4e87cd838

I suspect, that nixOS (and maybe other distributions, or systemd/elogind configurations) is assigning a different session path on resume from suspend than it was before suspend. And dms was only fetching the session path once, and maintaining it for the entire connection.

At least, it sounds plausible (and if so the above commit should solve it, since it explicitly re-fetches the session path from loginctl at every call - and if there's a mis-match re-subscribes to the new one)

I couldn't find conclusive evidence or docs about this actually being the case, though

**Comment by bokicoder** [comment]
I tried it, but it didn't work.

**Comment by bbedward** [comment]
Can you dump these:

Before suspend (when working) and after suspend (when not working)

```bash
loginctl list-sessions
loginctl list-sessions
loginctl show-session $(loginctl show-user $USER -p Display --value) -a
```

Also do you run dms via systemd user unit, or via compositor startup. (I will try that myself tbh, really wanna re-create this scenario)

**Comment by bokicoder** [comment]
> Can you dump these:
> 
> Before suspend (when working) and after suspend (when not working)
> 
> loginctl list-sessions
> loginctl list-sessions
> loginctl show-session $(loginctl show-user $USER -p Display --value) -a
> 

<img width="702" height="963" alt="Image" src="https://github.com/user-attachments/assets/4827df81-b0c2-4c0e-9cf0-d5447a8be8a2" />

> Also do you run dms via systemd user unit, or via compositor startup. (I will try that myself tbh, really wanna re-create this scenario)

I'm using a systemd user unit, but I've tried both approaches and the problem persists in each case.

**Comment by bokicoder** [comment]
I conducted 10 consecutive suspend tests using the latest commits of dms and dms-cli. The screen successfully locked only once (during the 2nd or 3rd attempt).

**Comment by bokicoder** [comment]
I actually also experience occasional screen lock failures when using swayidle, though the frequency is lower—possibly similar to the success rate of dms.

**Comment by bokicoder** [comment]
@bbedward I have a few observations, and I hope they're helpful.

- lock before suspend.
  - dms - Failed to lock:
    <img width="1069" height="300" alt="Image" src="https://github.com/user-attachments/assets/0bcc926c-12a2-4efe-bbf8-fcd68cc1ecd3" />
  - swayidle - Locked successfully:
    <img width="1043" height="278" alt="Image" src="https://github.com/user-attachments/assets/25b51fbf-8244-4b98-af97-6f45cd28a298" />

- Lock, wait for 0.2 seconds, then unlock.
  - dms - Successfully locked and unlocked:
    <img width="1717" height="759" alt="Image" src="https://github.com/user-attachments/assets/90278e79-6e6c-46dd-b2d3-9d0cc7e5b665" />
  - swayidle - Locked successfully but not unlocked:
    <img width="1721" height="775" alt="Image" src="https://github.com/user-attachments/assets/fe419534-c56f-41fc-bbef-986bbb88e56d" />

**Comment by bbedward** [comment]
The lock before suspend issue, still is unknown to me (I can't reproduce it) - but it did work before I added the sleep inhibitor release?  Just with a 4-5 second delay.

Releasing the inhibitor shouldnt have caused any breakage though - since its only released when the lock surface is activated.

Your screenshot seems to potentially indicate a different issue though, in that dms didnt receive the loginctl lock event (inhibitor stayed active through suspend).

**Comment by bokicoder** [comment]
> but it did work before I added the sleep inhibitor release?  Just with a 4-5 second delay.

Yes.

**Comment by bbedward** [comment]
For the most part I'm at a loss on this, but here's another shot in the dark

https://github.com/AvengeMedia/DankMaterialShell/commit/bbe802037ea6987b687475843dcd1e4c817441b7

https://github.com/AvengeMedia/danklinux/commit/1ff276828b382996733e4c0e8626e3c8e043b999

**Comment by bokicoder** [comment]
> For the most part I'm at a loss on this, but here's another shot in the dark
> 
> [bbe8020](https://github.com/AvengeMedia/DankMaterialShell/commit/bbe802037ea6987b687475843dcd1e4c817441b7)
> 
> [AvengeMedia/danklinux@1ff2768](https://github.com/AvengeMedia/danklinux/commit/1ff276828b382996733e4c0e8626e3c8e043b999)

It works! How does that work?

**Comment by bokicoder** [comment]
There is currently an issue where the sleep inhibitor is not being released when it should be. [1] This indicates a fundamental problem with the logic governing its creation and release, which needs to be thoroughly re-examined. A previous attempt to address this, such as the commit [2], should be reviewed as part of this process.

- [1] https://github.com/AvengeMedia/DankMaterialShell/issues/382#issuecomment-3400325697
- [2] https://github.com/AvengeMedia/DankMaterialShell/commit/9a305355c2bd9744309cc5609194b016c8e7b3c7

**Comment by bokicoder** [comment]
@bbedward I believe I have identified the root cause. I encountered the same 'lock before suspend' issue while using noctalia-shell. The problem was resolved immediately after I uninstalled `qtct` and `Kvantum` and set `QT_QPA_PLATFORMTHEME=gtk3`. This leads me to reasonably suspect that `QT_QPA_PLATFORMTHEME=qt5ct` and `Kvantum` are responsible for causing the lock screen to become slow and fail.
