### ISSUE TITLE
Configuration file "//.config/quickshellrc" not writable

### ISSUE THREAD

**Issue by prirai** [AvengeMedia/DankMaterialShell#624]
## Compositor

- [x] niri
- [ ] Hyprland
- [ ] dwl (MangoWC)
- [ ] sway
- [ ] Other (specify)

## Distribution

Arch (CachyOS)

## dms version

v0.3.4

## Description

I have setup dms-greeter according to the guide at [DankGreeter (dms-greeter)](https://danklinux.com/docs/dankgreeter/).

When the greeter has to show up, I get a popup saying 
> Configuration file "//.config/quickshellrc" not writable

![Image](https://github.com/user-attachments/assets/438878b8-0cb2-4d35-9916-453ad26137e5)

At this point I can click OK or press Return to go to login just fine but this popup appears everytime and is annoying.

I made an empty config file at ~/.config/quickshellrc but that doesn't help. Also tried changing to 666.

## Expected Behavior

There should be no such popup dialog.

## Steps to Reproduce

1. Simply follow the documentation link above without any changes whatsoever.
2. I haven't configured anything in greetd
3. I have done only the installation, the base config for niri and [syncing with DMS](https://danklinux.com/docs/dankgreeter/configuration#syncing-with-dms).

**Comment by bbedward** [comment]
i'm not really sure where this is coming from tbh - don't see it in quickshells code and its not a file attempting to be created from dms.

Can you paste the /etc/greetd/config.toml ?

**Comment by viper0825** [comment]
I also am experiencing this error.

**Comment by purian23** [comment]
> I also am experiencing this error.

Hi there, could you provide the info requested above: `/etc/greetd/config.toml` 
Also to note: we have added an auto sync feature: 
https://danklinux.com/docs/dankgreeter/configuration#automatic-sync-recommended

`dms greeter enable` / `dms greeter status` / `dms greeter sync`

Let us know if this does the trick.

**Comment by viper0825** [comment]
[terminal]
 The VT to run the greeter on. Can be "next", "current" or a number
designating the VT.
vt = 1

The default session, also known as the greeter.
[default_session]

`agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
with whatever you want started, such as `sway`.
command = "agreety --cmd /bin/sh"
`command = "dms-greeter --command hyprland"`

The user to run the command as. The privileges this user must have depends
on the greeter. A graphical greeter may for example require the user to be
in the `video` group.
user = "greeter"

**Comment by viper0825** [comment]
Did the dms greeter commands, rebooted and still get the error message.  Everything works fine once you click OK button.

**Comment by purian23** [comment]
Got it, thanks for the report. We're discussing it.

**Comment by prirai** [comment]
How I fixed it:

In root shell:
```
useradd -r -g greeter -d /var/lib/greeter -s /sbin/nologin     -c "System Greeter" greeter
mkdir /var/lib/greeter
mkdir /var/lib/greeter/.config
touch /var/lib/greeter/.config/quickshellrc
chown greeter:greeter /var/lib/greeter -R
usermod -aG greeter myuser
```

Contents of `/etc/greetd/config.toml`:
```
[terminal]
vt = 1

[default_session]
command = "dms-greeter --command niri -C /etc/greetd/niri.kdl"
user = "myuser"
```

Keeping user as `greeter` also had the same issue. After following the above, the issue got fixed.

Source:
[1]: [https://download.copr.fedorainfracloud.org/results/avengemedia/danklinux/fedora-42-x86_64/09693338-dms-greeter/dms-greeter.spec](https://download.copr.fedorainfracloud.org/results/avengemedia/danklinux/fedora-42-x86_64/09693338-dms-greeter/dms-greeter.spec)

**Comment by purian23** [comment]
Thanks, we fixed permissions in `dms greeter sync` that should have resolved this in the future.

**Comment by ItaloCunhaBueno** [comment]
Hi, I'm having the same issue, I tried the solution above (which does work) but for some reason it adds a huge delay to the greeter list available desktop environments, and if I try to login with the DE list empty, the whole greeter freezes and I have to change tty session and restart the greeter, keeping the greeter user "greeter" in `/etc/greetd/config.toml` still show the quickshellrc message but there's no delay to list available DEs.

I already tried to run `dms greeter sync` multiple times, no change. Here's my system details:

```
dms doctor:
██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝
██║  ██║██╔══██║██║╚██╗██║██╔═██╗
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝

 System Health Check

──────────────────────────────────────

  System
    ● Operating System ····· CachyOS
    ● Architecture ········· amd64
    ● Display Server ······· Wayland

  Versions
    ● DMS CLI ·············· dms v1.4.3
    ● Quickshell ··········· quickshell 0.2.1, revision dacfa9de829ac7cb173825f593236bf2c21f637e, distributed by: CachyOS Linux
    ● DMS Shell ············ v1.4.3

  Installation
    ● DMS Configuration ···· Found
    ● shell.qml ············ Present

  Compositor
    ● niri ················· 25.11
    ○ Active ··············· niri

  Quickshell Features
    ● Polkit ··············· Available
    ● IdleMonitor ·········· Available
    ● IdleInhibitor ········ Available
    ● ShortcutInhibitor ···· Available

  Optional Features
    ● accountsservice ······ Available
    ● power-profiles-daemon  Available
    ● logind ··············· Available
    ● cups-pk-helper ······· Available
    ● I2C/DDC ·············· 2 monitor(s) detected
    ● qt6-imageformats ····· Installed (5 formats)
    ● kimageformats ········ Installed (4 formats)
    ● Terminal ············· kitty
    ● Network ·············· NetworkManager
    ● matugen ·············· Installed
    ● dgop ················· Installed
    ● cava ················· Installed
    ● khal ················· Installed
    ● danksearch ··········· Installed
    ● fprintd ·············· Installed

  Config Files
    ● settings.json ········ Present
    ● clsettings.json ······ Present
    ● plugin_settings.json · Present
    ● session.json ········· Present
    ● dms-colors.json ······ Present

  Services
    ● dms.service ·········· enabled, active
    ● greetd ··············· enabled

  Environment
    ○ QT_QPA_PLATFORMTHEME · qt6ct

  ──────────────────────────────────────
  ✓ All checks passed!


dms greeter status:
=== DMS Greeter Status ===

Greeter Configuration:
  ✓ Greeter is enabled
  Compositor: niri

Group Membership:
  ✓ User is in greeter group

Greeter Cache Directory:
  ✓ /var/cache/dms-greeter exists

Configuration Symlinks:
  ✓ Settings: synced correctly
  ✓ Session state: synced correctly
  ✓ Color theme: synced correctly

✓ All checks passed! Greeter is properly configured.

groups greeter:
greeter : greeter video

groups italo (my user):
italo : italo sys network wheel audio input lp storage video users rfkill docker i2c ollama gamemode greeter

cat /etc/greetd/config.toml
[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "/usr/bin/dms-greeter --command niri -C /etc/greetd/niri/config.kdl"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"

```

Let me know if any more information is necessary. Thanks.
