### ISSUE TITLE
[Feature] Add elogind support

### ISSUE THREAD

**Issue by psygiulio** [AvengeMedia/DankMaterialShell#86]
## Feature Description

I think it could be useful to add support for elogind, since the syntax for PowerActions and IdleInhibitor service is slightly different than from systemd.

## Use Case

I am running quickshell on void linux, having it compiled from its project page. However it seems it will be packaged for void's package manager in the near future (I cannot guarantee it), and the default setup in void doesn't use systemd.
Although it should be expected that a user with niche setups as the know-how to adjust stuff by itself, there are possible solutions that I think could be easy to adapt and solve possible issues for less-experienced users.

### 1. Edit to README

Add the systemd requirement (it should be obvious at least for the idle inhibitor service, as it's stated that it creates a systemd idle inhibitor; but it doesn't state so for Power Actions), or possibly in manual install instructions add the need for systemd OR the need to adapt elogind (if you intend to support its use).

A possible way, would be to tell the user to add a shell alias (but I am not sure if this method works), to 'translate' systemctl -> loginctl, and systemd-inhibit -> elogind-inhibit commands.
Alternatively, just warn the user that it requires systemd and it is his/her responsibility to adjust accordingly.

### 2. Edit to PowerConfirmModal.qml, LockScreenContent.qml  and IdleInhibitorService.qml

I don't know how feasible these edits are (to avoid unnecesary burden on you for a few possible users), since I do not know qml. However I will describe the edits here and what I thought could be done:

In PowerConfirmModal.qml and LockScreenContent.qml I simply changed the Quickshell.execDetached commands:
```
Quickshell.execDetached(["systemctl", "suspend"]) -->> Quickshell.execDetached(["loginctl", "suspend"])
Quickshell.execDetached(["systemctl", "reboot"]) -->> Quickshell.execDetached(["loginctl", "reboot"])
Quickshell.execDetached(["systemctl", "poweroff"]) -->> Quickshell.execDetached(["loginctl", "poweroff"])
```

In IdleInhibitorService.qml, the return value of idleInhibitProcess (line 50), was changed to:
```
return [
    "systemd-inhibit"  -->> "elogind-inhibit",
    "--what=idle",
    "--who=quickshell",
    "--why=" + inhibitReason,
    "--mode=block",
    "sleep", "infinity"
];
```

These changes could, according to my unserstanding, be adapted using a variable. However I am not sure of a proper way to identify if user has systemd/elogind, what comes to mind is a quick conditional check but I do not know how to implement it (the thing would be, trying to run cmd systemctl -h or loginctl -h  and parse exit code to determine if cmd exists).
Similarly, I did not mention it but the other instance of systemd in the whole project is in DgopService.qml, where it simply determines the icon to show on process list (function getProcessIcon at line 464), there is could similarly be included for elogind. => Moreover I don't know if the process names are fetched using dgop or qml, but this way could be a possible solution to the above problem of identifying if user has systemd or elogind.

Lastly, thanks for your work on bringing this awesome project.

**Comment by bbedward** [comment]
Could you give the output of these

 ```bash
ps -eo comm= | grep -Fx elogind
echo $?
```

just want to see about a mechanism to detect elogind, probably will run something like that on startup and just swap out the systemd specific stuff with elogind specific stuff.

```bash
❯ ps -eo comm= | grep -Fx systemd-logind
systemd-logind
❯ echo $?
0
```

Example of what it looks like with systemd ^, I assume that would return a 0 exit code on systems with elogind, or maybe theres a more reliable way to detect it.

**Comment by jalappy** [comment]
This way it works because the process is elogind-daemon (I double-checked with btop and dgop after the initial lack of grep results):
```
$ ps -eo comm= | grep -Fx elogind-daemon
elogind-daemon
$ echo $?
0
```
And, just in case it may be needed,, the results of `ps -eo comm= | grep elogind` are the two elogind processes running on system:
```
$ ps -eo comm= | grep elogind
elogind-daemon
elogind-inhibit
```

**Comment by bbedward** [comment]
Give it a try I pushed up elogind support

**Comment by mac-a-r0ni** [comment]
I've been building this on slackware (another elogind system) and I've been looking for clues of where to find the code, I thought maybe it was hard-coded quickshell data, but I'd not found anything yet. Glad to see this here and I'll also try out the latest git on slackware and report back. 

P.S. dankmaterialshell is really good right out the gate. Thank you so much for this awesomeness.

**Comment by bbedward** [comment]
@mac-a-r0ni  I consolidated it [here](https://github.com/AvengeMedia/DankMaterialShell/blob/master/Services/SessionService.qml) now to centralize the inhibit/poweroff/suspend stuff. That's where elogind one lives now

**Comment by jalappy** [comment]
I am unable to try the latest changes right now, because I installed quickshell without Hyprland support (see below for the build config I used) and as you can see here I am not unable to start it. 

```
INFO: Launching config: "/home/user/.config/quickshell/Dank/shell.qml"
  INFO: Shell ID: "52df48750f6160f876a53a745a879994" Path ID "52df48750f6160f876a53a745a879994"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/20j9ape1t/log.qslog"
 ERROR: Failed to load configuration
 ERROR:   caused by @shell.qml[25:5]: Type WallpaperBackground unavailable
 ERROR:   caused by @Modules/WallpaperBackground.qml[59:29]: Type DankIcon unavailable
 ERROR:   caused by @Widgets/DankIcon.qml[4:1]: Type StyledText unavailable
 ERROR:   caused by @Widgets/StyledText.qml[-1:-1]: Type Anims unavailable
 ERROR:   caused by @Common/Anims.qml[-1:-1]: Type AppUsageHistoryData unavailable
 ERROR:   caused by @Common/AppUsageHistoryData.qml[-1:-1]: Type Appearance unavailable
 ERROR:   caused by @Common/Appearance.qml[-1:-1]: Type CacheUtils unavailable
 ERROR:   caused by @Common/CacheUtils.qml[-1:-1]: Type ModalManager unavailable
 ERROR:   caused by @Common/ModalManager.qml[-1:-1]: Type Paths unavailable
 ERROR:   caused by @Common/Paths.qml[-1:-1]: Type SessionData unavailable
 ERROR:   caused by @Common/SessionData.qml[-1:-1]: Type CalendarService unavailable
 ERROR:   caused by @Services/CalendarService.qml[-1:-1]: Type CavaService unavailable
 ERROR:   caused by @Services/CavaService.qml[-1:-1]: Type CompositorService unavailable
 ERROR:   caused by @Services/CompositorService.qml[8:1]: module "Quickshell.Hyprland" is not installed
  WARN: QThreadStorage: Thread 0x7fd2981f0290 exited after QThreadStorage 2 destroyed
  WARN: QThreadStorage: Thread 0x7fd2981f0290 exited after QThreadStorage 1 destroyed
```

I still have as DankMaterialShell the version I downloaded 2-3 days ago (and on which I started modifying some parts to fit my system). So I will now look at your commits and try to apport the changes you did (without breaking it, possibly) in order to test it (if it still makes sense?), or else I will rebuild quickshell (preferably, if you can tell me if you built it or which distro package you used, I can look at the build setup used and replicate it)

Anyway, here is how I build quickshell:

```
cmake -GNinja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCRASH_REPORTER=OFF -DESCREENCOPY_HYPRLAND_TOPLEVEL=OFF -DX11=OFF -DHYPRLAND=OFF -DHYPRLAND_GLOBAL_SHORTUCS=OFF -DHYPRLAND_FOCUS_GRAB=OFF -DI3=OFF -DI3_IPC=OFF
```

And, lastly, I agree, thanks for the work (and sorry for the extra one for this, I will fix it and give feedback)

**Comment by jalappy** [comment]
Update 1:
I did a quick check, removing the `import Quickshell.Hyprland` line from CompositorService and HyprlandService, and elogind integration is now flawless, tested on process monitor, power actions and idle inhibitor, all works.

Regarding the other part, I guess it simply means an user should install quickshell without removing parts, I don't think this has to be fixed (I mean, it's useful to have the compositor detection and hyprland integration, this is on me)

**Comment by bbedward** [comment]
I mean, in theory it's possible to separate out anything that depends on `Quickshell.Hyprland` and use `Loader` to load those components only if niri isnt detected, but I think it's too complicated for probably not much gain of compiling without hyprland (I assume, it's a pretty lightweight addition - I have no detectable higher memory usage or anything, so probably just a slightly bigger quickshell binary is all it results in)

**Comment by mac-a-r0ni** [comment]
> [@mac-a-r0ni](https://github.com/mac-a-r0ni) I consolidated it [here](https://github.com/AvengeMedia/DankMaterialShell/blob/master/Services/SessionService.qml) now to centralize the inhibit/poweroff/suspend stuff. That's where elogind one lives now

Thank you, and I've tested it all in niri so far (I've yet to setup a dank-hypr config) and it's all working as expected. Sleep, reboot, shutdown all respond appropriately (logout worked already). Thank you for this!

**Comment by jalappy** [comment]
I agree, thank you for your suggestions!
I use this thread to quickly ask if it's alright if I submit a couple more of feature/suggestions? (each in their appropriate thread I mean)

Both would be related to theming, but I don't want to bother with unnecessary issues if the current efforts are probably elsewhere. Basically one would be related to matugen generation (in the version of 2-3d ago it was all in one single script that used a config.toml in the project instead of user one, I have yet to check if latest script integrates matugen user's configs or how it is handled), 

While the other would be related to niri's color config, since I could not get matugen's generated colors to affect niri (and neither I seem to make it work now), so I modified briefly Colors.qml to modify niri's user config (but again I would first check latest commits to see how it is handled now and if it still applies)

**Comment by bbedward** [comment]
First one, matugen is just running its own config still. Enhancement to also run user ones could be added.

For niri, I actually don’t want to risk messing with a users niri configuration which is why there’s really nothing there.

I have an open PR on niri to introduce config merging (so you could have multiple layout {} blacks and so forth)

That is meant to be a pre requisite to a modular config system in niri so you could have imports, then the idea would be to just be able to import the generated colors in the niri config and it just works. Think it’s a bit too risky to mess with the niri config directly though. So hopefully that work gets merged into niri soon-ish

**Comment by jalappy** [comment]
Okay, thank you! I will keep integrating as is now then and wait for changes on niri's part! 

(Anyway for matugen I simply removed the -C option, using user's config and copied gtk/qt templates over there, along my own; while for niri I simply added in matugen's template the whole layout block, and called from Color.qml the following execDispatch instead of generating a niri-colours.kdl, but ofc a modular system as you did is better once the PR on niri's part will be completed)

```
Quickshell.execDetached(
          ["bash", "-c", `cp ~/.config/DankMaterialShell/niri_base.kdl ~/.config/DankMaterialShell/config.kdl && echo '${content}' >> ~/.config/DankMaterialShell/config.kdl && mv ~/.config/DankMaterialShell/config.kdl ~/.config/niri/config.kdl`])
```

In any case, I thank you again for your patience, I'll take my leave now!
